### ISSUE TITLE
Hive数据库建模

### ISSUE THREAD

**Issue by ZhangRuige** [ZhangRuige/easyDataInsightV1.0#12]

**Comment by ShiZengHua-zy** [comment]
Hive数据库建模初版
![edi_erm_v1](https://cloud.githubusercontent.com/assets/15188745/10878590/b3df046c-8189-11e5-84c4-9848ccb73ba2.png)

**Comment by ShiZengHua-zy** [comment]
今天：
模型已转化成hsql，目前部分还有错，不能执行到hive,需要再检查修改；
接下来工作：
主要是完成对nutch进来的数据做转化。

**Comment by ShiZengHua-zy** [comment]
对表做了一些调整，加了一些字段，修改了字段名表名，加了mysql的表，最新如下
![edi_erm_v2 0](https://cloud.githubusercontent.com/assets/15188745/11061092/62dc8736-87df-11e5-8873-47beb4421f66.png)

**Comment by ShiZengHua-zy** [comment]
对模型做了调整，将hive结构和mysql结构做了分离，并按导出的表格式完成了创建脚本。脚本见项目[wiki](https://github.com/ZhangRuige/easyDataInsightV1.0/wiki/hive&mysql_table_create_script)
hive:
![edi_erm_v2 1](https://cloud.githubusercontent.com/assets/15188745/11089676/a3ebabf4-88a6-11e5-9351-cb02cbda1243.png)

mysql:
![edi_mysql_erm_v1 0](https://cloud.githubusercontent.com/assets/15188745/11089695/c4df26e2-88a6-11e5-9722-ce63e6d26d8b.png)
