### ISSUE TITLE
分词、词性标注设计开发

### ISSUE THREAD

**Issue by ZhangRuige** [ZhangRuige/easyDataInsightV1.0#17]

**Comment by WuYang12** [comment]
今天的工作：
完成了基于规则的观点提取简单模型的代码编写
待解决的问题：
1.完善模型里的词典
2.完成观点分类
3.改善情感值算法

**Comment by WuYang12** [comment]
这两天的工作：
1.调试代码，确定模型训练部分和生产部分各自包含的内容
2.研究词典扩充方法，准备专利申请材料
接下来的计划：
1.完成词典扩充方法的研究，测试可行性，完成专利申请材料
2.在hadoop上测试情感分析算法

**Comment by WuYang12** [comment]
今天的工作：
按照上周五讨论的树结构，对代码进行了修改。已经基本完成。
明天开始继续研究词典扩充算法。
