### ISSUE TITLE
文本分类设计开发

### ISSUE THREAD

**Issue by ZhangRuige** [ZhangRuige/easyDataInsightV1.0#18]

**Comment by WuYang12** [comment]
今天的进展
完成代码编写：使用w2v算法计算词向量，用词向量给评论对象分类。
未来的工作
1.情感计算
2.词典构造

**Comment by WuYang12** [comment]
今天的工作：
基本完成观点提取和分类，情感分类相关算法的代码调试。能够正常与HIVE进行对接。
明天的计划：
继续完善观点提取的方法，提高算法分析结果的准确性。
