### ISSUE TITLE
网页动态内容抓取

### ISSUE THREAD

**Issue by ZhangRuige** [ZhangRuige/easyDataInsightV1.0#20]

**Comment by WangPing01** [comment]
这2天完成的工作：
    利用firefox浏览器内核和webkit浏览器内核，来模拟浏览器抓取jd上动态数据，已成功抓取到价格和评论总数。

碰到的问题：
    评论列表抓取不了。原因为京东的评论加载模式为：判断评论区是否在显示范围，若是则加载评论。而selenimu插件不能处理基于页面滚动的AJAX请求页面。

明天工作：
    更换nutch版本至1.8，使用nutch-htmlunit插件。

**Comment by WangPing01** [comment]
今天成功运行HtmlUnit。抓取到的数据如下：评论区第一页内容。

    现在通过nutch能抓取的jd数据有：
        1、所有手机商品的ID，即所有手机商品的URL。
        2、基本属性：标题，价格，评论总数，品牌，型号和商品ID。
        3、评论区的第一页。

    针对现有能采集到的数据，需考虑新解决方案。
        1、需要定制一个新插件。
        2、该插件解决以下问题：
             a、抓取完整的网页源码，包括价格、评论总数；
             b、解析出商品基本属性(包括价格，评论总数)；
             c、获取评论第一页，并组装URL获取其他的评论页面。
             d、将商品属性、评论数据按商品类别，保存到本地或hdfs里。

明天给出新方案。

**Comment by WangPing01** [comment]
当前爬虫模块进度：
        1、重新确定目前的基本架构：以nutch2.3为基础，修改protocol-s2jh插件，使之适用jd。
        2、爬取jd数据的思路：
              静态信息，从html文本中解析。
              动态数据，拼接url获取：价格，评论总数，评论列表。
今日完成工作：
       1、解析出商品基本属性，即网页内容的静态信息：标题，商品ID，品牌，型号，颜色，规格参数。
       2、抓取到所有手机目录下所有商品。

碰到的问题：
      1、解决apache-gora-mongodb字符编码，导致本地存取失败的问题。
           https://issues.apache.org/jira/browse/GORA-388

      2、bin/nutch generate命令的-topN参数问题，导致商品获取不全。而自己一开始没发现这个问题，
         调试过程中花费太多时间。

明天工作：
1、获取页面动态数据。
2、考虑如何将爬取下的数据传递出去(传递到哪、以何种方式传递)。

**Comment by WangPing01** [comment]
今天工作：
1、测试可成功获取jd全部手机产品。
2、可成功获取动态数据：价格，评论总数。

碰到的问题：
1、评论回复处理问题。
    和吴杨讨论后，决定暂时不处理评论的回复。
    原因如下：
            1)、评论的回复来自jd的一个论坛。需要用爬虫去抓取，而不是目前的url直接获取。
            2)、评论回复的处理，相当于处理论坛的数据，需对上下文进行关联。所以待后期处理论坛数据    时，同时处理。
2、隐患，需考虑时间问题。
    一页评论（10条）内容，即一个json，大小约为20k。
    一个商品10w条评论，即1w个json，则约有200k数据。

明天工作：
1、继续抓取评论列表。
2、考虑如何将解析后的数据传递出去。

**Comment by WangPing01** [comment]
今天完成工作：
1、成功获取一个商品的完整评论列表。
2、解析出的评论数据暂时存在mysql数据库。
