### ISSUE TITLE
迭代一系统集成

### ISSUE THREAD

**Issue by ZhangRuige** [ZhangRuige/easyDataInsightV1.0#25]

**Comment by ShiZengHua-zy** [comment]
除与爬虫数据的集成后面都一串通。

**Comment by ShiZengHua-zy** [comment]
今天自己再加过了一些数据测试，从hdfs如hive、中间结算、统计、直到导出到mysql都已串通。接下来打算将串通的这些脚本模块化，抽取参数，使其能通用。还有完成新词发现的算法的部分开发。
