### ISSUE TITLE
迭代二系统集成

### ISSUE THREAD

**Issue by ZhangRuige** [ZhangRuige/easyDataInsightV1.0#26]

**Comment by ShiZengHua-zy** [comment]
已完成：
1.原计划输入方式的源数据导入集成（现在需要调整）；
2.情感分析算法的集成；
3.情感分析结果汇总；
4.按分区增量同步指定表数据到mysq;
5.mysql数据备份（edi db需要修改成，按指定表备份）；
未完成:
1.源数据导入集成调整;
2.edi db需要修改成，按指定表备份;
3.配置到linux自动执行，完成部分。

**Comment by ShiZengHua-zy** [comment]
已完成：
1.源数据导入集成调整;
2.edi db需要修改成，按指定表备份;
3.配置到linux自动执行，完成部分。
未完成：
1.情感分析、新词提取未实现增量计算；
2.product新数据入库和同步mysql还需要再调试；
3.mysql前端建模。

**Comment by ShiZengHua-zy** [comment]
今天完成:
1.评论提及提取初版设计，交互图及数据库模型见[wiki](https://github.com/ZhangRuige/easyDataInsightV1.0/wiki/%E8%AF%84%E8%AE%BA%E5%85%B6%E4%BB%96%E5%93%81%E7%89%8C%E5%9E%8B%E5%8F%B7%E6%8F%90%E5%8F%8A%E7%9A%84%E6%8F%90%E5%8F%96%E6%96%B9%E6%B3%95%E8%AE%BE%E8%AE%A1)；
2.讨论得出UI交互原型，见wangp发出的原型设计。
接下来工作：
1.确定提及提取设计；
2.若需要修改上面设计，开始开发该功能。

**Comment by ShiZengHua-zy** [comment]
今天工作：
1.提及功能开发；
2.完成买家分布数据统计；
3.价格走势、销量、买家分布统计方法讨论，界面交互讨论；
明天工作计划：
继续提及功能开发，同步数据到mysql。

**Comment by ShiZengHua-zy** [comment]
今天工作：
1.提及功能与算法接口整合；
2.完成买家分布数据同步数据到mysql；
明天工作计划：
1.继续提及功能开发，同步数据到mysql。
2.别名配置及从配置表生成提及提取程序的词典。

**Comment by ShiZengHua-zy** [comment]
今天完成工作：
1.提及提取统计开发，型号总评论（销量）统计；
2.mysql server重新部署；
3.自动更新商品型号的实现过程记录；
明天计划：
1.继续提及功能开发；
2,新数据入库程序修改；
3.完成mysql自动备份并上传到hdfs.

**Comment by ShiZengHua-zy** [comment]
今天完成工作：
1.继续提及功能开发；
2,新数据入库程序修改；
3.完成mysql自动备份并上传到hdfs.
未完成：
1.提及功能未按计划完成，遇到了商品数据不规则导致不能提取到品牌型号的问题。
