### ISSUE TITLE
Hadoop环境搭建

### ISSUE THREAD

**Issue by ZhangRuige** [ZhangRuige/easyDataInsightV1.0#3]

**Comment by ShiZengHua-zy** [comment]
今天工作内容：
1.继续完善实施方案文档；
2.本地安装vmware，linux准备hadoop编译环境；
3.完成了hadoop本地库、eclipse开发插件编译的部分工作，目前。
接下来计划：
1.继续完成hadoop编译，解决编译过程中遇到的问题；
2.安装hadoop伪分布式环境，验证hive安装方案。

**Comment by ShiZengHua-zy** [comment]
今天工作内容：
1.已完成hadoop编译；
2.已验证并修改了hive安装方案；
接下来计划：
完成hive安装及配置方法验证。

**Comment by ShiZengHua-zy** [comment]
今天工作内容：
1.完成hive安装及配置方法验证;
2.完成hadoop开发插件hadoop-eclipse-plugin的编译，安装配置，并已调试到可以连接到集群正常工作。
接下来计划：
验证hive

**Comment by ShiZengHua-zy** [comment]
今天工作内容：
1.完成hive安装及配置方法验证;
2.完成hadoop开发插件hadoop-eclipse-plugin的编译，安装配置，并已调试到可以连接到集群正常工作。
接下来计划：
1.验证hive大数据量更新的可行性;
2.找出数据存入和读取的方案，并尝试验证。

**Comment by ShiZengHua-zy** [comment]
今天工作内容：
1.解决开发环境hadoop开发插件使用过程中的访问权限、类库引用等问题。
2.确定集群数据存入和读取用hive JDBC操作hive。
接下来计划：
1.验证hive大数据量更新的可行性。

**Comment by ShiZengHua-zy** [comment]
今天工作内容：
1.对使用java api调用hdfs\RM\hive操作做了测试，更新了安装实施方案。
接下来计划：
1.尝试完成shell操作hive的示例，提前完成一些代码编写结构；
2.验证hive大数据量更新的实际性能（因为本地环境转移预计在阿里云环境搭建好后做，有性能验证结果得出是否可行）。

**Comment by ShiZengHua-zy** [comment]
今天主要时间花在了开发机器转移，笔记本被收走了，转台式机遇到也麻烦，下午了解了hadoop集群安全控制和资源监控的内容，并试验了用linux job执行shell脚本操作hive，明天计划继续测试用shell做其他操作，并整理脚本。

**Comment by ShiZengHua-zy** [comment]
Hadoop环境搭建准备工作已就绪，就等部署了。今天工作内容请见https://github.com/ZhangRuige/easyDataInsightV1.0/issues/2

**Comment by ShiZengHua-zy** [comment]
云环境hadoop的namenode,datanode1，以及mysql，hive已部署成功。
接下来部署datanode2。

**Comment by ShiZengHua-zy** [comment]
datanode2部署还没做，因为花不了几分钟，下次机群启动时配置。
