### ISSUE TITLE
商品规格数据解析

### ISSUE THREAD

**Issue by shizenghua123** [ZhangRuige/easyDataInsightV1.0#30]
今天商品规格数据解析完成50%，原来这部分是直接存储的html代码，根据需求需要解析并推送到前台mysql.

**Comment by ShiZengHua-zy** [comment]
今天完成商品规格数据解析。接下来：1.测试并推送到mysql；2.解决新词提取数据量大的问题。

**Comment by ShiZengHua-zy** [comment]
今天完成：
1.测试并推送到mysql，2.整合新词提起训练，测试发现训练所需时间太久，讨论后要修改为不再为每次提取训练新模型，定期更新模型的方式。
明天：
1.做上述修改。2.手机选机页面数据计算方式规划及实施。
