### ISSUE TITLE
爬虫工具部署

### ISSUE THREAD

**Issue by ZhangRuige** [ZhangRuige/easyDataInsightV1.0#5]

**Comment by WangPing01** [comment]
今天尝试在win7系统上编译、部署nutch2.3，还有点工作尚未完成，明天继续。

**Comment by WangPing01** [comment]
今天部署了nutch2.3，安装试用后，发现这个版本还存在很多问题。需借鉴成熟方案里使用的版本，然后做出自己选择。
明天计划：
1、确定nutch的版本问题。
2、单机上安装试用nutch。
3、给出数据爬取的方案，并考虑如何集成到系统里。

**Comment by WangPing01** [comment]
今天完成了：
1、确定使用nutch1.10，solr4.10.4。
2、单机上安装试用了nutch。
下周一计划：
1、尝试从京东上爬取我们需要数据。

**Comment by WangPing01** [comment]
1、从jd上抓取到了部分产品页。尚未对页面进行分析。
2、目前考虑的方案是：用nutch将所有网页爬取下来，存到本地的webdb，然后建立索引供sorl作搜索。
我考虑了另外一个方案：由于电商网站，产品的url都是规则性的，以jd为例：http://item.jd.com/1618201.html，其中数字串1618201，即为该产品的ID。那么，可否在“手机”目录下取得所有产品的ID列表，然后遍历所有的手机商品页面，抓取所需的信息。当然，这只针对电商网站适用。

**Comment by WangPing01** [comment]
这2天利用nutch从jd上抓取了很多商品数据，但有个问题：商品价格、评论数、评论详情等都没值，即动态数据获取不到。今天从允许nutch使用parse-js插件，以及配置网址过滤条件这两个角度，试图解决该问题，效果明天再测试。后面还要使用模拟浏览器来获取动态数据，。
明天计划：
    继续今天的任务。

**Comment by WangPing01** [comment]
今天完成了工作：
     1、修改nutch 1.10源码，从而避开了京东商城的robots声明。
     2、分析网址过滤规则，获取到jd手机目录、商品详情和前后页的网址。
     3、通过以上两步的改进，可以精确获取到jd商城手机目录下手机商品网址和前后页网址。从而可以抓取到所有手机商品。

碰到的问题：
     商品价格、评论数、评论详情的值还是未抓取到。

明天任务：
     在Nutch中嵌入模拟浏览器获取动态数据。

**Comment by WangPing01** [comment]
今天工作：
1、集成protocol selenium插件，该插件调用firefox内核，来渲染网页，以便得到AJAX结果。编译该插件后，在win 7的cygwin环境里运行出错。
明天任务：
2、将nutch1.10+solr4.10.4部署到ubuntu 14.04.3虚拟机系统里。
2、获取商品价格、评论数和评论详情的值。
