### ISSUE TITLE
中文NLP算法研究

### ISSUE THREAD

**Issue by ZhangRuige** [ZhangRuige/easyDataInsightV1.0#6]
观点提取、情感分析

**Comment by WuYang12** [comment]
算法旨在从评论数据中提取用户的观点，并在此之上进行情感分析
拟将算法分成3个主要步骤：
1.抽取评论对象
2.提取观点句
3.情感分析
目前还在研究相关的论文和研究成果，寻找合适的算法...

**Comment by WuYang12** [comment]
主要研究了抽取评论对象的算法，现在比较常用的模型有HMM（隐马尔科夫链模型）和CRF（条件随机场），各有特点，具体优缺点如下：
HMM对模型做了较强的假设，但是有较快的训练速度和计算速度
CRF有较好的对象抽取效果，不需要对观测值和状态之间做独立的假设，但是训练速度和计算速度较慢
接下来的计划：
明天准备研究情感分析方面的相关方法

**Comment by WuYang12** [comment]
情感分类的方法主要有两类：
1.基于情感词的方法
2.机器学习方法
基于情感词的算法相对简单，但是需要情感词库以及情感值的标记
机器学习方法的关键是提取特征，特征选择的好坏直接影响算法的准确性，常用的分类算法有NB，SVM，最大熵等

通过这三天对于观点提取和情感分析的学习，基本了解相关步骤和常用算法。
接下来的工作计划：打算使用相关工具包，选择合适的算法来实现情感分析的过程，并尝试对比各种工具包的效果好坏。

**Comment by WuYang12** [comment]
初步确定算法步骤，晚一些邮件给各位，有时间大家讨论一下

发现CRF的一个开源工具CRF++，对 特征模板文件 还没完全理解，明天继续研究其用法。

**Comment by WuYang12** [comment]
研究了CRF++例子中的BaseNP特征模板，了解调用方法。该模板可以用于评论对象提取。
下周一计划：
做一个训练用的数据集，测试CRF算法效果

**Comment by WuYang12** [comment]
今天的进展：
使用CRF算法完成评论对象标注的测试。
接下来的计划：
参考相关资料，基于提取的评论对象，完成情感分类。

**Comment by WuYang12** [comment]
今天的进展：
1.使用CRF模型训练较大的训练集。
发现一个问题：通过CRF模型的标注结果都是训练集里的对象词，不会发现新的对象词。（可能是训练集的标注不够典型？）
2.学习了文本特征提取的CHI算法，文本特征将会被应用于情感分类的机器学习模型当中。
接下来的计划：
1.尝试解决CRF模型出现的问题，用半监督的方法对训练集进行评论对象标注。
2.研究svm开源工具libsvm的使用方法，结合CHI算法，完成情感分类。
3.使用情感词典匹配的方式，完成情感分类。并对比二者的分类结果。
