### ISSUE TITLE
前后台、hadoop、NLP、爬虫拉通

### ISSUE THREAD

**Issue by ZhangRuige** [ZhangRuige/easyDataInsightV1.0#9]
迭代1的总体目标！

**Comment by ShiZengHua-zy** [comment]
今天：
编写用hive的udf完成做情感分析算法计算的接口开发及测试，该接口可将情感分析的算法整合到hadoop执行。
接下来工作：
将hive数据模型导入到新建的mv集群，准备导入些数据做测试。

**Comment by ShiZengHua-zy** [comment]
昨天：
1.尝试用hive其他类型的自定义方法UDF，其中有些方法可能会很大程度减少后续手动开发量。
2.搭建机群，完成剩余的工作。
3.将之前建立的hive ER模型编写创建语句，部分已建立到本地库。
今天：
1.完成上面第三项；
2.准备开始著作权的事。

**Comment by ShiZengHua-zy** [comment]
今天：
1.上午些著作权文档；
2.下午修改表结构，编写hive库初始化脚本，创建表；
3.完成部分hive和分析算法的对接，未完成。
接下来的工作：
1.明天上午完成剩余对接，并导入假数据测试；
2.下午编写著作权文档；.
3.找方法让sqoop能导出分区表到mysql。

**Comment by ShiZengHua-zy** [comment]
与NPL整合基本完成，只是NPL还在报错，需要继续调整。
明天计划完成与sqoop整合遇到的问题和设计文档。
